### ISSUE TITLE
The result was bad.

### ISSUE THREAD

**Issue by wzylove** [Visual-AI/Inpaint4Drag#8]
Hello author, thank you very much for your work. When I was editing the eyes in my own image, this happened: when I pulled the eyes up, it created a blank space. What could be causing this?

<img width="1797" height="741" alt="Image" src="https://github.com/user-attachments/assets/99541037-2449-4056-b6c0-365cd83b1ccb" />

**Comment by LuJingyi-John** [comment]
Hi @wzylove, you can click the `Inpaint` button to fill the blank space

<img width="289" height="367" alt="Image" src="https://github.com/user-attachments/assets/654875c7-35c9-462c-9520-960e362917dc" />

**Comment by wzylove** [comment]
> 你好，你可以点击按钮填补空白`Inpaint`
> 
> <img alt="图像" width="289" height="367" src="https://private-user-images.githubusercontent.com/114227779/520469278-654875c7-35c9-462c-9520-960e362917dc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ0OTM3ODcsIm5iZiI6MTc2NDQ5MzQ4NywicGF0aCI6Ii8xMTQyMjc3NzkvNTIwNDY5Mjc4LTY1NDg3NWM3LTM1YzktNDYyYy05NTIwLTk2MGUzNjI5MTdkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEzMFQwOTA0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmVhNDUyMWVjYzMxZWUwYWMwODc3M2Q0Mzk1NWE2NDNmZTM0ODZmYjQ2MWVjMmI4YjQxNjk5Njc5NDFhZGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.v4hL9rhu9sS6lamU-OihTpzWxPDzxlV3vqiT94XVvdQ">

Thank you for your reply. I tried clicking the inpaint button and encountered the situation shown in the image below.

<img width="1362" height="597" alt="Image" src="https://github.com/user-attachments/assets/bc791a95-a47b-44be-ae4b-c1c9f6df4498" />

**Comment by LuJingyi-John** [comment]
Thank you for reporting the issue. 

Have you clicked the `Resize Image` button first? It seems that the inpainting mask is not correctly located. 

Or can you send me the testing image? I can record the process to help.

**Comment by wzylove** [comment]
> Thank you for reporting the issue.
> 
> Have you clicked the `Resize Image` button first? It seems that the inpainting mask is not correctly located.
> 
> Or can you send me the testing image? I can record the process to help.

This is a video I recorded of the operation process. Please take a look! If you need my images, please send me your email address and I will send them to you.

https://github.com/user-attachments/assets/140185f3-b648-45c8-87f7-2974b6536fab

**Comment by LuJingyi-John** [comment]
https://github.com/user-attachments/assets/87ba7cc5-360e-4a97-9cef-7bc2a3c50f2e

Would you mind checking this video for reference? You've followed the correct execution steps. However, the model performance is below expectations. Could you try restarting the app and ensuring that no changes have been made to the inpainting model?

**Comment by wzylove** [comment]
> issue_compressed.mov 
> Would you mind checking this video for reference? You've followed the correct execution steps. However, the model performance is below expectations. Could you try restarting the app and ensuring that no changes have been made to the inpainting model?

I tried restarting the program, but it's still the same. Is it because I haven't installed some dependencies? Also, could you tell me if the model in your video seems to have issues with eye detail?

<img width="1326" height="534" alt="Image" src="https://github.com/user-attachments/assets/c3b83659-74de-4ea4-a165-d35cc092a016" />

**Comment by LuJingyi-John** [comment]
<img width="1101" height="44" alt="Image" src="https://github.com/user-attachments/assets/2d06d823-a8ce-409f-98a9-13336e324e4c" />

Could you check if your terminal is displaying the loading progress correctly? The inpainting model we're using is [SD v1.5 Inpaint](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-inpainting), which is a powerful model that should handle details well.

**Comment by wzylove** [comment]
> <img alt="图像" width="1101" height="44" src="https://private-user-images.githubusercontent.com/114227779/520474076-2d06d823-a8ce-409f-98a9-13336e324e4c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ0OTcwNTAsIm5iZiI6MTc2NDQ5Njc1MCwicGF0aCI6Ii8xMTQyMjc3NzkvNTIwNDc0MDc2LTJkMDZkODIzLWE4Y2UtNDA5Zi05OGE5LTEzMzM2ZTMyNGU0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEzMFQwOTU5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjdjMzkyYjJiNzI0YjU3ZDAwY2Y2OWI3OTg2ZDYzMTU4ODE4Y2FjNjMwMzg5ZWY2ZjNmYWMyMjIyMjk3YmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2vZKyp3I3bU4QMOW5VO5vr_aZwRHqx9xKtothuJqwQs">
> 你能检查一下你的终端是否正确显示加载进度吗？我们使用的修复模型是[SD v1.5 Inpaint](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-inpainting)，这是一个功能强大的模型，应该能很好地处理细节。
Thank you, author. I was able to add it to the progress bar. I am also using the SD v1.5 Inpaint model, just like you. However, I am not using the file sd-v1-5-inpainting.ckpt. Is that the reason?
<img width="1158" height="327" alt="Image" src="https://github.com/user-attachments/assets/f783716a-ef00-4eed-baf0-41057ec157d0" />

**Comment by LuJingyi-John** [comment]
The progress bar you showed is for generating the image. However, I believe I've identified the issue: the model I'm using at [L185 in `utils/ui_utils.py`](https://github.com/Visual-AI/Inpaint4Drag/blob/main/utils/ui_utils.py#L185) is 'runwayml/stable-diffusion-inpainting', which has been deprecated. Could you please update the link to 'sd-legacy/stable-diffusion-inpainting'? This should resolve the problem. We'll push the changes shortly. Thank you so much for taking the time to report this issue. We really appreciate your help!

**Comment by wzylove** [comment]
> sd-legacy/stable-diffusion-inpainting

Thank you. This is my model address 'v1-5': ('/home/witai513/wzy/Inpaint4Drag/stable-diffusion-inpainting', '/home/witai513/wzy/Inpaint4Drag/lcm-lora-sdv1-5', '/home/witai513/wzy/Inpaint4Drag/taesd'). However, I downloaded these files manually from https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-inpainting/tree/main. Do I need to use the file sd-v1-5-inpainting.ckpt?

**Comment by LuJingyi-John** [comment]
No, you don't need to use the `sd-v1-5-inpainting.ckpt` file if you've downloaded the diffusers format files manually.

The `sd-v1-5-inpainting.ckpt` is the checkpoint format, while the other folders (`unet`, `vae`, `text_encoder`, etc.) are the diffusers format. Since you're using the diffusers pipeline in the code, you just need the folder structure you already downloaded, not the `.ckpt` file.

Your current setup with the folders should work fine!

**Comment by wzylove** [comment]
> No, you don't need to use the file if you've downloaded the diffusers format files manually.`sd-v1-5-inpainting.ckpt`
> 
> The is the checkpoint format, while the other folders (, , , etc.) are the diffusers format. Since you're using the diffusers pipeline in the code, you just need the folder structure you already downloaded, not the file.`sd-v1-5-inpainting.ckpt``unet``vae``text_encoder``.ckpt`

Okay, but I still can't fill in the blanks, even though I have all these files.

**Comment by LuJingyi-John** [comment]
I'm curious whether you've had a chance to update the model link following the steps below. Just wanted to check in!

> The progress bar you showed is for generating the image. However, I believe I've identified the issue: the model I'm using at [L185 in `utils/ui_utils.py`](https://github.com/Visual-AI/Inpaint4Drag/blob/main/utils/ui_utils.py#L185) is 'runwayml/stable-diffusion-inpainting', which has been deprecated. Could you please update the link to 'sd-legacy/stable-diffusion-inpainting'? This should resolve the problem. We'll push the changes shortly. Thank you so much for taking the time to report this issue. We really appreciate your help!

**Comment by wzylove** [comment]
> I'm curious whether you've had a chance to update the model link following the steps below. Just wanted to check in!
> 
> > The progress bar you showed is for generating the image. However, I believe I've identified the issue: the model I'm using at [L185 in `utils/ui_utils.py`](https://github.com/Visual-AI/Inpaint4Drag/blob/main/utils/ui_utils.py#L185) is 'runwayml/stable-diffusion-inpainting', which has been deprecated. Could you please update the link to 'sd-legacy/stable-diffusion-inpainting'? This should resolve the problem. We'll push the changes shortly. Thank you so much for taking the time to report this issue. We really appreciate your help!
I've always used the method of downloading the complete stable-diffusion-inpainting; this is my own path.
<img width="1689" height="759" alt="Image" src="https://github.com/user-attachments/assets/62b46de0-f3de-4019-ad95-10c796d575d4" />

**Comment by wzylove** [comment]
> I'm curious whether you've had a chance to update the model link following the steps below. Just wanted to check in!
> 
> > The progress bar you showed is for generating the image. However, I believe I've identified the issue: the model I'm using at [L185 in `utils/ui_utils.py`](https://github.com/Visual-AI/Inpaint4Drag/blob/main/utils/ui_utils.py#L185) is 'runwayml/stable-diffusion-inpainting', which has been deprecated. Could you please update the link to 'sd-legacy/stable-diffusion-inpainting'? This should resolve the problem. We'll push the changes shortly. Thank you so much for taking the time to report this issue. We really appreciate your help!

Could I add you on WeChat? I'd like to share my screen with you.

**Comment by LuJingyi-John** [comment]
Yes, my wechat is ljy1234asdf
